export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHANGE_NAME = "AUTH_CHANGE_NAME";
export const RESET_AUTH_ERROR = "RESET_AUTH_ERROR";

export const ADD_POST_START = "ADD_POST_START";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAIL = "ADD_POST_FAIL";
export const UPDATE_POST_COUNT = "UPDATE_POST_COUNT";
export const FETCH_POST_COUNT = "FETCH_POST_COUNT";
export const UPLOAD_PHOTO_START = "UPLOAD_PHOTO_START";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const DELETE_PHOTO = "DELETE_PHOTO";
export const SUBMIT_POST = "SUBMIT_POST";

export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const UPDATE_POST_ARRAY = "UPDATE_POST_ARRAY";

export const FETCH_PROFILE_INFO = "FETCH_PROFILE_INFO";
export const UPDATE_PROFILE_INFO = "UPDATE_PROFILE_INFO";
export const INITIALIZE_PROFILE = "INITIALIZE_PROFILE";
export const GENDER_CHANGE_HANDLER = "GENDER_CHANGE_HANDLER";
